"""Base class for all trading strategies."""

from __future__ import annotations

import importlib
import pkgutil
from abc import ABC, abstractmethod
from dataclasses import dataclass
from enum import Enum
from pathlib import Path
from typing import Any

import pandas as pd


class SignalType(str, Enum):
    """Types of trading signals generated by strategies."""

    # Buy signals (缠论买点)
    BUY_1 = "buy_1"   # 一买: bottom divergence at end of downtrend hub
    BUY_2 = "buy_2"   # 二买: first pullback after leaving hub
    BUY_3 = "buy_3"   # 三买: breakout above hub

    # Sell signals (缠论卖点)
    SELL_1 = "sell_1"  # 一卖: top divergence at end of uptrend hub
    SELL_2 = "sell_2"  # 二卖: first bounce after leaving hub
    SELL_3 = "sell_3"  # 三卖: breakdown below hub

    # Informational
    HUB_OSCILLATION = "hub_oscillation"  # 中枢震荡 — no clear direction


class SignalStrength(str, Enum):
    """Strength levels for trading signals."""

    STRONG = "strong"
    MODERATE = "moderate"
    WEAK = "weak"


@dataclass(frozen=True)
class Signal:
    """A single trading signal produced by a strategy.

    Attributes
    ----------
    date : str
        Date string in ``YYYY-MM-DD`` format.
    signal_type : SignalType
        The type of signal (buy/sell point classification).
    signal_strength : SignalStrength
        The strength of the signal.
    """

    date: str
    signal_type: SignalType
    signal_strength: SignalStrength

    def as_tuple(self) -> tuple[str, str, str]:
        """Return ``(date, signal_type, signal_strength)`` tuple."""
        return (self.date, self.signal_type.value, self.signal_strength.value)


class Strategy(ABC):
    """Abstract base class for all trading strategies.

    Subclasses must implement :meth:`generate_signals` which takes an OHLCV+MACD
    DataFrame and returns a list of :class:`Signal` objects.
    """

    @property
    @abstractmethod
    def name(self) -> str:
        """Unique strategy name (e.g. ``'chan_theory'``)."""
        ...

    @property
    @abstractmethod
    def display_name(self) -> str:
        """Human-readable display name (e.g. ``'缠论'``)."""
        ...

    @property
    @abstractmethod
    def timeframe(self) -> str:
        """Default timeframe (e.g. ``'1d'``)."""
        ...

    @abstractmethod
    def generate_signals(self, df: pd.DataFrame) -> list[Signal]:
        """Generate trading signals from OHLCV+MACD data.

        Parameters
        ----------
        df : pd.DataFrame
            Must contain columns: ``date, open, high, low, close, volume, macd``
            (and optionally ``dif, dea``).  Rows should be sorted by date ascending.

        Returns
        -------
        list[Signal]
            A list of :class:`Signal` objects, one per signal detected.
        """
        ...

    def get_params(self) -> list[dict[str, Any]]:
        """Return strategy parameters as a list of dicts (for API exposure)."""
        return []


# ---------------------------------------------------------------------------
# Strategy registry / loading
# ---------------------------------------------------------------------------

_STRATEGY_REGISTRY: dict[str, type[Strategy]] = {}


def register_strategy(cls: type[Strategy]) -> type[Strategy]:
    """Class decorator that registers a strategy in the global registry."""
    instance = cls()
    _STRATEGY_REGISTRY[instance.name] = cls
    return cls


def get_strategy(name: str) -> Strategy:
    """Instantiate a strategy by name.

    Raises
    ------
    KeyError
        If no strategy with the given name is registered.
    """
    if not _STRATEGY_REGISTRY:
        _discover_strategies()
    if name not in _STRATEGY_REGISTRY:
        raise KeyError(f"Unknown strategy: {name}")
    return _STRATEGY_REGISTRY[name]()


def list_strategies() -> list[str]:
    """Return names of all registered strategies."""
    if not _STRATEGY_REGISTRY:
        _discover_strategies()
    return sorted(_STRATEGY_REGISTRY.keys())


def _discover_strategies() -> None:
    """Import all modules in the ``src.strategy`` package to trigger registration."""
    pkg_path = Path(__file__).resolve().parent
    for _importer, modname, _ispkg in pkgutil.iter_modules([str(pkg_path)]):
        if modname == "base":
            continue
        importlib.import_module(f"src.strategy.{modname}")
